name: "build"

on:
  push:
    branches:
      - "main"
    paths-ignore:
      - '**/README.md'

  schedule:
    - cron: '0 6 * * *'  # Runs every day at 6 am UTC time

jobs:
  docker_buildx_debian:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
    
      - name: Install Requirements File
        run: pip install -r requirements.txt
    
      - name: Run Python script
        run: python create_nginx_lua_certbot_docker.py
    
      - name: Check if VERSION file exists
        run: |
          if [ ! -f "./build/VERSION" ]; then
            echo "VERSION file does not exist. Exiting build."
            exit 0
          fi
    
      - name: Get Version
        id: version
        run: echo "::set-output name=version::$(cat ./build/VERSION)"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          context: ./build/nginx-certbot/src
          file: ./build/nginx-certbot/src/Dockerfile
          platforms: |
            linux/arm64
            linux/arm/v7
            linux/amd64
            linux/386
          tags: |
            eyalerknet/nginx-lua-certbot:latest
            eyalerknet/nginx-lua-certbot:${{ steps.version.outputs.version }}
